%% EVALUACIÓN COMPLETA DE CALIBRACIÓN ESTÉREO
%
% Evalúa una calibración realizada con Stereo Camera Calibrator.
%
% Entrega:
% - Error medio de reproyección.
% - Parámetros intrínsecos.
% - Distorsión radial y tangencial.
% - Vector de traslación.
% - Matriz de rotación.
% - Baseline total.
% - Componente horizontal del baseline.
% - Gráficos de reproyección.
% - Gráfico de posiciones del tablero.
% - Rectificación de imágenes.
% - Anaglifos.
% - Error vertical después de rectificar.
% - Archivos CSV y TXT.
%
% Requiere:
% - Computer Vision Toolbox
% - stereoParams.mat
%
% ================================================================

clear;
clc;
close all;

%% ===============================================================
% CONFIGURACIÓN
% ================================================================

archivoCalibracion = 'stereoParams.mat';

carpetaCamaraIzquierda = fullfile( ...
    'calibracion', ...
    'izquierda');

carpetaCamaraDerecha = fullfile( ...
    'calibracion', ...
    'derecha');

extensionesPermitidas = { ...
    '*.png', ...
    '*.jpg', ...
    '*.jpeg', ...
    '*.bmp', ...
    '*.tif', ...
    '*.tiff'};

% Cantidad máxima de imágenes que se rectificarán.
% Usa Inf para procesar todas.
maxParesRectificados = 10;

carpetaResultados = ...
    'resultados_evaluacion_calibracion';

evaluarErrorVertical = true;

guardarImagenesRectificadas = true;

% Opciones:
% 'full'
% 'valid'
% 'same'
tipoSalidaRectificacion = 'full';

%% ===============================================================
% CREAR CARPETA DE RESULTADOS
% ================================================================

if ~exist(carpetaResultados, 'dir')
    mkdir(carpetaResultados);
end

%% ===============================================================
% CARGAR CALIBRACIÓN
% ================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('EVALUACIÓN DE CALIBRACIÓN ESTÉREO\n');
fprintf('============================================================\n');

if ~isfile(archivoCalibracion)
    error( ...
        'No se encontró el archivo: %s', ...
        archivoCalibracion);
end

datosCalibracion = load(archivoCalibracion);

nombresVariables = fieldnames(datosCalibracion);

stereoParams = [];
nombreVariableStereo = '';

for k = 1:numel(nombresVariables)

    nombreActual = nombresVariables{k};
    variableActual = datosCalibracion.(nombreActual);

    if isa(variableActual, 'stereoParameters')

        stereoParams = variableActual;
        nombreVariableStereo = nombreActual;

        break;
    end
end

if isempty(stereoParams)

    error( ...
        ['El archivo MAT no contiene una variable ' ...
         'de tipo stereoParameters.']);
end

fprintf( ...
    'Variable de calibración encontrada: %s\n', ...
    nombreVariableStereo);

camara1 = stereoParams.CameraParameters1;
camara2 = stereoParams.CameraParameters2;

%% ===============================================================
% INFORMACIÓN GENERAL
% ================================================================

tamanoImagen1 = camara1.ImageSize;
tamanoImagen2 = camara2.ImageSize;

errorGlobal = obtenerErrorReproyeccion(stereoParams);

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('RESUMEN GENERAL\n');
fprintf('------------------------------------------------------------\n');

fprintf( ...
    'Tamaño imagen cámara izquierda: %d x %d px\n', ...
    tamanoImagen1(2), ...
    tamanoImagen1(1));

fprintf( ...
    'Tamaño imagen cámara derecha:   %d x %d px\n', ...
    tamanoImagen2(2), ...
    tamanoImagen2(1));

if ~isnan(errorGlobal)

    fprintf( ...
        'Error medio de reproyección estéreo: %.4f px\n', ...
        errorGlobal);

else

    fprintf( ...
        'Error medio de reproyección estéreo: no disponible\n');
end

%% ===============================================================
% CÁMARA IZQUIERDA
% ================================================================

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('CÁMARA IZQUIERDA\n');
fprintf('------------------------------------------------------------\n');

mostrarParametrosCamara(camara1);

%% ===============================================================
% CÁMARA DERECHA
% ================================================================

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('CÁMARA DERECHA\n');
fprintf('------------------------------------------------------------\n');

mostrarParametrosCamara(camara2);

%% ===============================================================
% PARÁMETROS EXTRÍNSECOS
% ================================================================

R = stereoParams.RotationOfCamera2;
T = stereoParams.TranslationOfCamera2;

baseline = norm(T);
baselineHorizontal = abs(T(1));

angulosEuler = matrizRotacionAAngulos(R);

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('RELACIÓN ENTRE LAS DOS CÁMARAS\n');
fprintf('------------------------------------------------------------\n');

fprintf('Vector de traslación de la cámara 2:\n');
fprintf('Tx = %.6f\n', T(1));
fprintf('Ty = %.6f\n', T(2));
fprintf('Tz = %.6f\n', T(3));

fprintf('\n');

fprintf( ...
    'Baseline total estimado     = %.6f unidades\n', ...
    baseline);

fprintf( ...
    'Separación horizontal |Tx|  = %.6f unidades\n', ...
    baselineHorizontal);

fprintf( ...
    '%s\n', ...
    ['La unidad del baseline es la misma usada para ' ...
     'definir el tamaño de los cuadrados del tablero.']);

fprintf('\n');
fprintf('Matriz de rotación de la cámara 2:\n');

disp(R);

fprintf( ...
    'Rotación aproximada alrededor de X: %.6f grados\n', ...
    angulosEuler(1));

fprintf( ...
    'Rotación aproximada alrededor de Y: %.6f grados\n', ...
    angulosEuler(2));

fprintf( ...
    'Rotación aproximada alrededor de Z: %.6f grados\n', ...
    angulosEuler(3));

%% ===============================================================
% COMPROBACIONES AUTOMÁTICAS
% ================================================================

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('COMPROBACIONES AUTOMÁTICAS\n');
fprintf('------------------------------------------------------------\n');

evaluarParametrosFisicos(camara1, 'izquierda');
evaluarParametrosFisicos(camara2, 'derecha');

%% ===============================================================
% GUARDAR RESUMEN TXT
% ================================================================

archivoResumen = fullfile( ...
    carpetaResultados, ...
    'resumen_calibracion.txt');

guardarResumenTexto( ...
    archivoResumen, ...
    stereoParams, ...
    errorGlobal, ...
    baseline, ...
    baselineHorizontal, ...
    angulosEuler);

fprintf('\n');
fprintf('Resumen guardado en:\n');
fprintf('%s\n', archivoResumen);

%% ===============================================================
% GRÁFICO DE ERRORES DE REPROYECCIÓN
% ================================================================

try

    figuraError = figure( ...
        'Name', ...
        'Errores de reproyección', ...
        'NumberTitle', ...
        'off');

    showReprojectionErrors(stereoParams);

    if ~isnan(errorGlobal)

        title( ...
            sprintf( ...
                'Errores de reproyección - Media = %.4f px', ...
                errorGlobal));

    else

        title('Errores de reproyección');
    end

    archivoGraficoError = fullfile( ...
        carpetaResultados, ...
        'errores_reproyeccion.png');

    exportgraphics( ...
        figuraError, ...
        archivoGraficoError, ...
        'Resolution', ...
        200);

catch ME

    warning( ...
        'No fue posible mostrar los errores: %s', ...
        ME.message);
end

%% ===============================================================
% GRÁFICO DE POSICIONES DEL TABLERO
% ================================================================

try

    figuraExtrinsecos = figure( ...
        'Name', ...
        'Posiciones del tablero', ...
        'NumberTitle', ...
        'off');

    showExtrinsics( ...
        stereoParams, ...
        'CameraCentric');

    title( ...
        'Posiciones del tablero respecto de las cámaras');

    archivoGraficoExtrinsecos = fullfile( ...
        carpetaResultados, ...
        'posiciones_tablero.png');

    exportgraphics( ...
        figuraExtrinsecos, ...
        archivoGraficoExtrinsecos, ...
        'Resolution', ...
        200);

catch ME

    warning( ...
        'No fue posible mostrar los extrínsecos: %s', ...
        ME.message);
end

%% ===============================================================
% BUSCAR IMÁGENES
% ================================================================

archivosIzquierda = buscarImagenes( ...
    carpetaCamaraIzquierda, ...
    extensionesPermitidas);

archivosDerecha = buscarImagenes( ...
    carpetaCamaraDerecha, ...
    extensionesPermitidas);

if isempty(archivosIzquierda) || isempty(archivosDerecha)

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('RECTIFICACIÓN NO REALIZADA\n');
    fprintf('------------------------------------------------------------\n');

    fprintf( ...
        ['No se encontraron imágenes en una o ambas ' ...
         'carpetas de calibración.\n']);

    fprintf( ...
        'Carpeta izquierda: %s\n', ...
        carpetaCamaraIzquierda);

    fprintf( ...
        'Carpeta derecha:   %s\n', ...
        carpetaCamaraDerecha);

else

    %% ===========================================================
    % CANTIDAD DE IMÁGENES
    % ============================================================

    cantidadIzquierda = numel(archivosIzquierda);
    cantidadDerecha = numel(archivosDerecha);

    cantidadPares = min( ...
        cantidadIzquierda, ...
        cantidadDerecha);

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('IMÁGENES DE CALIBRACIÓN\n');
    fprintf('------------------------------------------------------------\n');

    fprintf( ...
        'Imágenes izquierdas encontradas: %d\n', ...
        cantidadIzquierda);

    fprintf( ...
        'Imágenes derechas encontradas:   %d\n', ...
        cantidadDerecha);

    fprintf( ...
        'Pares disponibles:               %d\n', ...
        cantidadPares);

    if cantidadIzquierda ~= cantidadDerecha

        warning( ...
            ['La cantidad de imágenes izquierdas y derechas ' ...
             'no coincide. Se usarán %d pares.'], ...
            cantidadPares);
    end

    if isinf(maxParesRectificados)

        cantidadEvaluada = cantidadPares;

    else

        cantidadEvaluada = min( ...
            cantidadPares, ...
            maxParesRectificados);
    end

    fprintf( ...
        'Pares que serán evaluados:       %d\n', ...
        cantidadEvaluada);

    %% ===========================================================
    % CARPETA DE RECTIFICADAS
    % ============================================================

    carpetaRectificadas = fullfile( ...
        carpetaResultados, ...
        'imagenes_rectificadas');

    if guardarImagenesRectificadas && ...
            ~exist(carpetaRectificadas, 'dir')

        mkdir(carpetaRectificadas);
    end

    %% ===========================================================
    % VARIABLES DE ERROR VERTICAL
    % ============================================================

    numeroPar = [];
    puntosDetectados = [];
    errorVerticalMedio = [];
    errorVerticalMediano = [];
    errorVerticalMaximo = [];
    errorVerticalRMS = [];

    %% ===========================================================
    % PROCESAR PARES
    % ============================================================

    for i = 1:cantidadEvaluada

        fprintf('\n');

        fprintf( ...
            'Procesando par %d de %d...\n', ...
            i, ...
            cantidadEvaluada);

        rutaIzquierda = archivosIzquierda{i};
        rutaDerecha = archivosDerecha{i};

        fprintf( ...
            'Izquierda: %s\n', ...
            rutaIzquierda);

        fprintf( ...
            'Derecha:   %s\n', ...
            rutaDerecha);

        imagenIzquierda = imread(rutaIzquierda);
        imagenDerecha = imread(rutaDerecha);

        %% Comprobar dimensiones

        dimensionesIzquierda = size(imagenIzquierda);
        dimensionesDerecha = size(imagenDerecha);

        altoIzquierda = dimensionesIzquierda(1);
        anchoIzquierda = dimensionesIzquierda(2);

        altoDerecha = dimensionesDerecha(1);
        anchoDerecha = dimensionesDerecha(2);

        if altoIzquierda ~= tamanoImagen1(1) || ...
                anchoIzquierda ~= tamanoImagen1(2)

            warning( ...
                ['El par izquierdo %d tiene tamaño %d x %d, ' ...
                 'pero la calibración utiliza %d x %d.'], ...
                i, ...
                anchoIzquierda, ...
                altoIzquierda, ...
                tamanoImagen1(2), ...
                tamanoImagen1(1));
        end

        if altoDerecha ~= tamanoImagen2(1) || ...
                anchoDerecha ~= tamanoImagen2(2)

            warning( ...
                ['El par derecho %d tiene tamaño %d x %d, ' ...
                 'pero la calibración utiliza %d x %d.'], ...
                i, ...
                anchoDerecha, ...
                altoDerecha, ...
                tamanoImagen2(2), ...
                tamanoImagen2(1));
        end

        %% Rectificación

        try

            [rectificadaIzquierda, rectificadaDerecha] = ...
                rectifyStereoImages( ...
                    imagenIzquierda, ...
                    imagenDerecha, ...
                    stereoParams, ...
                    'OutputView', ...
                    tipoSalidaRectificacion);

        catch ME

            warning( ...
                'No fue posible rectificar el par %d: %s', ...
                i, ...
                ME.message);

            continue;
        end

        %% Anaglifo

        anaglifo = stereoAnaglyph( ...
            rectificadaIzquierda, ...
            rectificadaDerecha);

        %% Guardar imágenes

        if guardarImagenesRectificadas

            nombreBase = sprintf( ...
                'par_%03d', ...
                i);

            archivoIzquierdaRectificada = fullfile( ...
                carpetaRectificadas, ...
                [nombreBase '_izquierda.png']);

            archivoDerechaRectificada = fullfile( ...
                carpetaRectificadas, ...
                [nombreBase '_derecha.png']);

            archivoAnaglifo = fullfile( ...
                carpetaRectificadas, ...
                [nombreBase '_anaglifo.png']);

            archivoComparacion = fullfile( ...
                carpetaRectificadas, ...
                [nombreBase '_comparacion.png']);

            imwrite( ...
                rectificadaIzquierda, ...
                archivoIzquierdaRectificada);

            imwrite( ...
                rectificadaDerecha, ...
                archivoDerechaRectificada);

            imwrite( ...
                anaglifo, ...
                archivoAnaglifo);

            comparacion = imtile( ...
                { ...
                    rectificadaIzquierda, ...
                    rectificadaDerecha ...
                }, ...
                'GridSize', ...
                [1 2]);

            imwrite( ...
                comparacion, ...
                archivoComparacion);
        end

        %% Mostrar primer anaglifo

        if i == 1

            figuraRectificacion = figure( ...
                'Name', ...
                'Primer par rectificado', ...
                'NumberTitle', ...
                'off');

            imshow(anaglifo);

            title( ...
                ['Anaglifo rectificado: los puntos correspondientes ' ...
                 'deben quedar a la misma altura']);

            archivoPrimerAnaglifo = fullfile( ...
                carpetaResultados, ...
                'primer_anaglifo_rectificado.png');

            exportgraphics( ...
                figuraRectificacion, ...
                archivoPrimerAnaglifo, ...
                'Resolution', ...
                200);
        end

        %% =======================================================
        % ERROR VERTICAL DEL TABLERO
        % ========================================================

        if evaluarErrorVertical

            try

                [puntosIzquierda, tamanoTableroIzquierda] = ...
                    detectCheckerboardPoints( ...
                        rectificadaIzquierda);

                [puntosDerecha, tamanoTableroDerecha] = ...
                    detectCheckerboardPoints( ...
                        rectificadaDerecha);

                tablerosValidos = ...
                    ~isempty(puntosIzquierda) && ...
                    ~isempty(puntosDerecha) && ...
                    isequal( ...
                        tamanoTableroIzquierda, ...
                        tamanoTableroDerecha) && ...
                    size(puntosIzquierda, 1) == ...
                    size(puntosDerecha, 1);

                if tablerosValidos

                    puntosDerechaCorregidos = ...
                        corregirOrdenPuntos( ...
                            puntosIzquierda, ...
                            puntosDerecha, ...
                            tamanoTableroDerecha);

                    diferenciaVertical = abs( ...
                        puntosIzquierda(:, 2) - ...
                        puntosDerechaCorregidos(:, 2));

                    numeroPar(end + 1, 1) = i;

                    puntosDetectados(end + 1, 1) = ...
                        size(puntosIzquierda, 1);

                    errorVerticalMedio(end + 1, 1) = ...
                        mean( ...
                            diferenciaVertical, ...
                            'omitnan');

                    errorVerticalMediano(end + 1, 1) = ...
                        median( ...
                            diferenciaVertical, ...
                            'omitnan');

                    errorVerticalMaximo(end + 1, 1) = ...
                        max(diferenciaVertical);

                    errorVerticalRMS(end + 1, 1) = ...
                        sqrt( ...
                            mean( ...
                                diferenciaVertical.^2, ...
                                'omitnan'));

                    fprintf( ...
                        'Puntos detectados:       %d\n', ...
                        size(puntosIzquierda, 1));

                    fprintf( ...
                        'Error vertical medio:    %.4f px\n', ...
                        errorVerticalMedio(end));

                    fprintf( ...
                        'Error vertical mediano:  %.4f px\n', ...
                        errorVerticalMediano(end));

                    fprintf( ...
                        'Error vertical máximo:   %.4f px\n', ...
                        errorVerticalMaximo(end));

                    fprintf( ...
                        'Error vertical RMS:      %.4f px\n', ...
                        errorVerticalRMS(end));

                    imagenPuntos = ...
                        visualizarPuntosRectificados( ...
                            rectificadaIzquierda, ...
                            rectificadaDerecha, ...
                            puntosIzquierda, ...
                            puntosDerechaCorregidos);

                    if guardarImagenesRectificadas

                        nombreBase = sprintf( ...
                            'par_%03d', ...
                            i);

                        archivoPuntos = fullfile( ...
                            carpetaRectificadas, ...
                            [nombreBase ...
                             '_puntos_detectados.png']);

                        imwrite( ...
                            imagenPuntos, ...
                            archivoPuntos);
                    end

                else

                    fprintf( ...
                        ['No se pudo detectar el mismo tablero ' ...
                         'en ambas imágenes rectificadas.\n']);
                end

            catch ME

                warning( ...
                    ['No se pudo evaluar el error vertical ' ...
                     'del par %d: %s'], ...
                    i, ...
                    ME.message);
            end
        end
    end

    %% ===========================================================
    % RESULTADOS DEL ERROR VERTICAL
    % ============================================================

    if ~isempty(numeroPar)

        tablaErrorVertical = table( ...
            numeroPar, ...
            puntosDetectados, ...
            errorVerticalMedio, ...
            errorVerticalMediano, ...
            errorVerticalMaximo, ...
            errorVerticalRMS, ...
            'VariableNames', ...
            { ...
                'Par', ...
                'PuntosDetectados', ...
                'ErrorVerticalMedio_px', ...
                'ErrorVerticalMediano_px', ...
                'ErrorVerticalMaximo_px', ...
                'ErrorVerticalRMS_px' ...
            });

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');
        fprintf('ERROR VERTICAL DESPUÉS DE RECTIFICAR\n');
        fprintf('------------------------------------------------------------\n');

        disp(tablaErrorVertical);

        archivoTablaVertical = fullfile( ...
            carpetaResultados, ...
            'error_vertical_rectificacion.csv');

        writetable( ...
            tablaErrorVertical, ...
            archivoTablaVertical);

        errorVerticalGlobal = mean( ...
            errorVerticalMedio, ...
            'omitnan');

        errorVerticalMedianoGlobal = median( ...
            errorVerticalMediano, ...
            'omitnan');

        errorVerticalMaximoGlobal = max( ...
            errorVerticalMaximo);

        fprintf( ...
            'Error vertical medio global:   %.4f px\n', ...
            errorVerticalGlobal);

        fprintf( ...
            'Mediana vertical global:       %.4f px\n', ...
            errorVerticalMedianoGlobal);

        fprintf( ...
            'Máximo vertical global:        %.4f px\n', ...
            errorVerticalMaximoGlobal);

        %% Gráfico error vertical

        figuraVertical = figure( ...
            'Name', ...
            'Error vertical rectificado', ...
            'NumberTitle', ...
            'off');

        plot( ...
            numeroPar, ...
            errorVerticalMedio, ...
            '-o', ...
            'LineWidth', ...
            1.5);

        hold on;

        plot( ...
            numeroPar, ...
            errorVerticalMaximo, ...
            '-s', ...
            'LineWidth', ...
            1.5);

        yline( ...
            1, ...
            '--', ...
            'Referencia: 1 px', ...
            'LineWidth', ...
            1.2);

        grid on;

        xlabel('Número del par');
        ylabel('Diferencia vertical [px]');

        title( ...
            'Error vertical después de la rectificación');

        legend( ...
            'Error medio', ...
            'Error máximo', ...
            'Referencia de 1 px', ...
            'Location', ...
            'best');

        archivoGraficoVertical = fullfile( ...
            carpetaResultados, ...
            'grafico_error_vertical.png');

        exportgraphics( ...
            figuraVertical, ...
            archivoGraficoVertical, ...
            'Resolution', ...
            200);

    else

        fprintf('\n');

        fprintf( ...
            ['No se obtuvieron mediciones válidas ' ...
             'del error vertical.\n']);
    end
end

%% ===============================================================
% EXPORTAR PARÁMETROS PRINCIPALES
% ================================================================

tablaParametros = table( ...
    errorGlobal, ...
    baseline, ...
    baselineHorizontal, ...
    T(1), ...
    T(2), ...
    T(3), ...
    angulosEuler(1), ...
    angulosEuler(2), ...
    angulosEuler(3), ...
    camara1.FocalLength(1), ...
    camara1.FocalLength(2), ...
    camara2.FocalLength(1), ...
    camara2.FocalLength(2), ...
    camara1.PrincipalPoint(1), ...
    camara1.PrincipalPoint(2), ...
    camara2.PrincipalPoint(1), ...
    camara2.PrincipalPoint(2), ...
    'VariableNames', ...
    { ...
        'ErrorReproyeccion_px', ...
        'BaselineTotal', ...
        'BaselineHorizontal_absTx', ...
        'Tx', ...
        'Ty', ...
        'Tz', ...
        'RotacionX_grados', ...
        'RotacionY_grados', ...
        'RotacionZ_grados', ...
        'Fx_Camara1_px', ...
        'Fy_Camara1_px', ...
        'Fx_Camara2_px', ...
        'Fy_Camara2_px', ...
        'Cx_Camara1_px', ...
        'Cy_Camara1_px', ...
        'Cx_Camara2_px', ...
        'Cy_Camara2_px' ...
    });

archivoParametrosCSV = fullfile( ...
    carpetaResultados, ...
    'parametros_principales.csv');

writetable( ...
    tablaParametros, ...
    archivoParametrosCSV);

%% ===============================================================
% MENSAJE FINAL
% ================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('EVALUACIÓN FINALIZADA\n');
fprintf('============================================================\n');

fprintf( ...
    'Baseline total estimado:    %.6f unidades\n', ...
    baseline);

fprintf( ...
    'Componente horizontal |Tx|: %.6f unidades\n', ...
    baselineHorizontal);

if ~isnan(errorGlobal)

    fprintf( ...
        'Error medio de reproyección: %.4f px\n', ...
        errorGlobal);
end

fprintf('\n');
fprintf('Resultados guardados en:\n');
fprintf('%s\n', carpetaResultados);

%% ===============================================================
% FUNCIONES LOCALES
% ================================================================

function mostrarParametrosCamara(parametrosCamara)

    focal = parametrosCamara.FocalLength;
    centro = parametrosCamara.PrincipalPoint;
    radial = parametrosCamara.RadialDistortion;
    tangencial = parametrosCamara.TangentialDistortion;

    fprintf( ...
        'Distancia focal Fx: %.6f px\n', ...
        focal(1));

    fprintf( ...
        'Distancia focal Fy: %.6f px\n', ...
        focal(2));

    fprintf( ...
        'Punto principal Cx: %.6f px\n', ...
        centro(1));

    fprintf( ...
        'Punto principal Cy: %.6f px\n', ...
        centro(2));

    fprintf( ...
        'Skew: %.8f\n', ...
        parametrosCamara.Skew);

    fprintf('Distorsión radial:\n');

    if isempty(radial)

        fprintf('No disponible.\n');

    else

        for j = 1:numel(radial)

            fprintf( ...
                'k%d = %.10f\n', ...
                j, ...
                radial(j));
        end
    end

    fprintf('Distorsión tangencial:\n');

    if isempty(tangencial)

        fprintf( ...
            'No estimada o desactivada.\n');

    else

        for j = 1:numel(tangencial)

            fprintf( ...
                'p%d = %.10f\n', ...
                j, ...
                tangencial(j));
        end
    end

    if isprop( ...
            parametrosCamara, ...
            'MeanReprojectionError')

        fprintf( ...
            'Error medio individual: %.4f px\n', ...
            parametrosCamara.MeanReprojectionError);
    end
end


function errorMedio = obtenerErrorReproyeccion(stereoParams)

    errorMedio = NaN;

    if isprop( ...
            stereoParams, ...
            'MeanReprojectionError')

        errorMedio = ...
            stereoParams.MeanReprojectionError;

        return;
    end

    try

        errores1 = ...
            stereoParams.CameraParameters1.ReprojectionErrors;

        errores2 = ...
            stereoParams.CameraParameters2.ReprojectionErrors;

        magnitudes1 = sqrt( ...
            errores1(:, 1, :).^2 + ...
            errores1(:, 2, :).^2);

        magnitudes2 = sqrt( ...
            errores2(:, 1, :).^2 + ...
            errores2(:, 2, :).^2);

        todosLosErrores = [ ...
            magnitudes1(:); ...
            magnitudes2(:)];

        errorMedio = mean( ...
            todosLosErrores, ...
            'omitnan');

    catch

        errorMedio = NaN;
    end
end


function archivos = buscarImagenes( ...
    carpeta, ...
    extensiones)

    archivos = {};

    if ~exist(carpeta, 'dir')
        return;
    end

    listadoCompleto = [];

    for j = 1:numel(extensiones)

        listadoExtension = dir( ...
            fullfile( ...
                carpeta, ...
                extensiones{j}));

        listadoCompleto = [ ...
            listadoCompleto; ...
            listadoExtension]; %#ok<AGROW>
    end

    if isempty(listadoCompleto)
        return;
    end

    nombres = {listadoCompleto.name};

    nombres = ordenarNombresNaturalmente(nombres);

    archivos = cell( ...
        numel(nombres), ...
        1);

    for j = 1:numel(nombres)

        archivos{j} = fullfile( ...
            carpeta, ...
            nombres{j});
    end
end


function nombresOrdenados = ...
    ordenarNombresNaturalmente(nombres)

    nombresMinuscula = lower( ...
        string(nombres));

    [~, indices] = sort(nombresMinuscula);

    nombresOrdenados = nombres(indices);
end


function angulos = matrizRotacionAAngulos(R)

    valor = sqrt( ...
        R(1, 1)^2 + ...
        R(2, 1)^2);

    esSingular = valor < 1e-8;

    if ~esSingular

        anguloX = atan2( ...
            R(3, 2), ...
            R(3, 3));

        anguloY = atan2( ...
            -R(3, 1), ...
            valor);

        anguloZ = atan2( ...
            R(2, 1), ...
            R(1, 1));

    else

        anguloX = atan2( ...
            -R(2, 3), ...
            R(2, 2));

        anguloY = atan2( ...
            -R(3, 1), ...
            valor);

        anguloZ = 0;
    end

    angulos = rad2deg( ...
        [ ...
            anguloX, ...
            anguloY, ...
            anguloZ ...
        ]);
end


function evaluarParametrosFisicos( ...
    parametrosCamara, ...
    nombreCamara)

    tamano = parametrosCamara.ImageSize;

    alto = tamano(1);
    ancho = tamano(2);

    focal = parametrosCamara.FocalLength;
    centro = parametrosCamara.PrincipalPoint;
    radial = parametrosCamara.RadialDistortion;

    fprintf( ...
        'Cámara %s:\n', ...
        nombreCamara);

    if centro(1) < 0 || centro(1) > ancho

        fprintf( ...
            ['  ADVERTENCIA: Cx = %.3f px está fuera ' ...
             'del ancho de la imagen.\n'], ...
            centro(1));

    else

        fprintf( ...
            '  Cx está dentro de la imagen.\n');
    end

    if centro(2) < 0 || centro(2) > alto

        fprintf( ...
            ['  ADVERTENCIA: Cy = %.3f px está fuera ' ...
             'del alto de la imagen.\n'], ...
            centro(2));

    else

        fprintf( ...
            '  Cy está dentro de la imagen.\n');
    end

    relacionFocalImagen = ...
        max(focal) / max(alto, ancho);

    if relacionFocalImagen > 10

        fprintf( ...
            ['  ADVERTENCIA: la distancia focal supera ' ...
             'ampliamente las dimensiones de la imagen.\n']);
    end

    if any(abs(radial) > 100)

        fprintf( ...
            ['  ADVERTENCIA: existen coeficientes de ' ...
             'distorsión radial de gran magnitud.\n']);
    end

    diferenciaFocal = ...
        abs(focal(1) - focal(2)) / mean(focal);

    fprintf( ...
        '  Diferencia relativa entre Fx y Fy: %.4f %%\n', ...
        100 * diferenciaFocal);

    fprintf('\n');
end


function puntosCorregidos = corregirOrdenPuntos( ...
    puntosReferencia, ...
    puntosObjetivo, ...
    tamanoTablero)

    puntosCorregidos = puntosObjetivo;

    candidatos = cell(4, 1);

    candidatos{1} = puntosObjetivo;
    candidatos{2} = flipud(puntosObjetivo);

    try

        filas = tamanoTablero(1) - 1;
        columnas = tamanoTablero(2) - 1;

        cantidadEsperada = filas * columnas;

        if cantidadEsperada ~= size(puntosObjetivo, 1)

            error( ...
                ['La cantidad de puntos no coincide ' ...
                 'con el tamaño del tablero.']);
        end

        matrizX = reshape( ...
            puntosObjetivo(:, 1), ...
            columnas, ...
            filas)';

        matrizY = reshape( ...
            puntosObjetivo(:, 2), ...
            columnas, ...
            filas)';

        %% Inversión horizontal

        candidatoHorizontalX = fliplr(matrizX);
        candidatoHorizontalY = fliplr(matrizY);

        candidatoHorizontalXTranspuesto = ...
            candidatoHorizontalX';

        candidatoHorizontalYTranspuesto = ...
            candidatoHorizontalY';

        candidatos{3} = [ ...
            candidatoHorizontalXTranspuesto(:), ...
            candidatoHorizontalYTranspuesto(:) ...
        ];

        %% Inversión total

        candidatoTotalX = flipud( ...
            fliplr(matrizX));

        candidatoTotalY = flipud( ...
            fliplr(matrizY));

        candidatoTotalXTranspuesto = ...
            candidatoTotalX';

        candidatoTotalYTranspuesto = ...
            candidatoTotalY';

        candidatos{4} = [ ...
            candidatoTotalXTranspuesto(:), ...
            candidatoTotalYTranspuesto(:) ...
        ];

    catch ME

        warning( ...
            'No se pudieron reorganizar los puntos: %s', ...
            ME.message);

        candidatos{3} = puntosObjetivo;
        candidatos{4} = flipud(puntosObjetivo);
    end

    mejorError = Inf;

    for k = 1:numel(candidatos)

        candidato = candidatos{k};

        if isempty(candidato)
            continue;
        end

        if size(candidato, 1) ~= ...
                size(puntosReferencia, 1)

            continue;
        end

        if size(candidato, 2) ~= 2
            continue;
        end

        diferenciasVerticales = abs( ...
            puntosReferencia(:, 2) - ...
            candidato(:, 2));

        diferenciasVerticales = ...
            diferenciasVerticales( ...
                ~isnan(diferenciasVerticales));

        if isempty(diferenciasVerticales)
            continue;
        end

        errorActual = mean( ...
            diferenciasVerticales);

        if errorActual < mejorError

            mejorError = errorActual;
            puntosCorregidos = candidato;
        end
    end
end


function imagenResultado = visualizarPuntosRectificados( ...
    imagenIzquierda, ...
    imagenDerecha, ...
    puntosIzquierda, ...
    puntosDerecha)

    if ndims(imagenIzquierda) == 2

        imagenIzquierda = repmat( ...
            imagenIzquierda, ...
            [1 1 3]);
    end

    if ndims(imagenDerecha) == 2

        imagenDerecha = repmat( ...
            imagenDerecha, ...
            [1 1 3]);
    end

    imagenIzquierdaPuntos = insertMarker( ...
        imagenIzquierda, ...
        puntosIzquierda, ...
        'o', ...
        'Size', ...
        5);

    imagenDerechaPuntos = insertMarker( ...
        imagenDerecha, ...
        puntosDerecha, ...
        'o', ...
        'Size', ...
        5);

    imagenResultado = imtile( ...
        { ...
            imagenIzquierdaPuntos, ...
            imagenDerechaPuntos ...
        }, ...
        'GridSize', ...
        [1 2]);
end


function guardarResumenTexto( ...
    nombreArchivo, ...
    stereoParams, ...
    errorGlobal, ...
    baseline, ...
    baselineHorizontal, ...
    angulosEuler)

    camara1 = stereoParams.CameraParameters1;
    camara2 = stereoParams.CameraParameters2;

    T = stereoParams.TranslationOfCamera2;
    R = stereoParams.RotationOfCamera2;

    fid = fopen( ...
        nombreArchivo, ...
        'w');

    if fid == -1

        warning( ...
            'No se pudo crear el archivo de resumen.');

        return;
    end

    limpiezaArchivo = onCleanup( ...
        @() fclose(fid)); %#ok<NASGU>

    fprintf( ...
        fid, ...
        'EVALUACIÓN DE CALIBRACIÓN ESTÉREO\n');

    fprintf( ...
        fid, ...
        '=================================\n\n');

    if ~isnan(errorGlobal)

        fprintf( ...
            fid, ...
            'Error medio de reproyección: %.6f px\n', ...
            errorGlobal);

    else

        fprintf( ...
            fid, ...
            'Error medio de reproyección: no disponible\n');
    end

    fprintf( ...
        fid, ...
        'Baseline total: %.6f unidades\n', ...
        baseline);

    fprintf( ...
        fid, ...
        'Componente horizontal |Tx|: %.6f unidades\n\n', ...
        baselineHorizontal);

    fprintf( ...
        fid, ...
        'VECTOR DE TRASLACIÓN\n');

    fprintf( ...
        fid, ...
        'Tx = %.10f\n', ...
        T(1));

    fprintf( ...
        fid, ...
        'Ty = %.10f\n', ...
        T(2));

    fprintf( ...
        fid, ...
        'Tz = %.10f\n\n', ...
        T(3));

    fprintf( ...
        fid, ...
        'ÁNGULOS DE ROTACIÓN APROXIMADOS\n');

    fprintf( ...
        fid, ...
        'Rotación X = %.10f grados\n', ...
        angulosEuler(1));

    fprintf( ...
        fid, ...
        'Rotación Y = %.10f grados\n', ...
        angulosEuler(2));

    fprintf( ...
        fid, ...
        'Rotación Z = %.10f grados\n\n', ...
        angulosEuler(3));

    fprintf( ...
        fid, ...
        'MATRIZ DE ROTACIÓN\n');

    for fila = 1:3

        fprintf( ...
            fid, ...
            '%.10f  %.10f  %.10f\n', ...
            R(fila, 1), ...
            R(fila, 2), ...
            R(fila, 3));
    end

    fprintf( ...
        fid, ...
        '\nCÁMARA IZQUIERDA\n');

    escribirCamaraEnArchivo( ...
        fid, ...
        camara1);

    fprintf( ...
        fid, ...
        '\nCÁMARA DERECHA\n');

    escribirCamaraEnArchivo( ...
        fid, ...
        camara2);
end


function escribirCamaraEnArchivo( ...
    fid, ...
    camara)

    fprintf( ...
        fid, ...
        'Fx = %.10f px\n', ...
        camara.FocalLength(1));

    fprintf( ...
        fid, ...
        'Fy = %.10f px\n', ...
        camara.FocalLength(2));

    fprintf( ...
        fid, ...
        'Cx = %.10f px\n', ...
        camara.PrincipalPoint(1));

    fprintf( ...
        fid, ...
        'Cy = %.10f px\n', ...
        camara.PrincipalPoint(2));

    fprintf( ...
        fid, ...
        'Skew = %.10f\n', ...
        camara.Skew);

    fprintf( ...
        fid, ...
        'Distorsión radial: ');

    for k = 1:numel(camara.RadialDistortion)

        fprintf( ...
            fid, ...
            '%.10f ', ...
            camara.RadialDistortion(k));
    end

    fprintf(fid, '\n');

    fprintf( ...
        fid, ...
        'Distorsión tangencial: ');

    for k = 1:numel(camara.TangentialDistortion)

        fprintf( ...
            fid, ...
            '%.10f ', ...
            camara.TangentialDistortion(k));
    end

    fprintf(fid, '\n');

    if isprop( ...
            camara, ...
            'MeanReprojectionError')

        fprintf( ...
            fid, ...
            'Error medio individual = %.10f px\n', ...
            camara.MeanReprojectionError);
    end
end