%% ANALISIS OFFLINE DE VIDEOS ESTEREO EN MATLAB
% Procesa videos ya grabados. NO captura cámaras.
%
% Funciones:
% 1) carga stereoParams.mat;
% 2) abre dos videos existentes;
% 3) rectifica los frames;
% 4) permite seleccionar alineación horizontal y ROI;
% 5) aplica CLAHE;
% 6) calcula bordes Canny como diagnóstico;
% 7) calcula disparidad con disparitySGM;
% 8) reconstruye profundidad 3D;
% 9) calcula altura de espuma respecto de una altura de referencia;
% 10) muestra durante el procesamiento:
%       - video rectificado;
%       - video CLAHE;
%       - video de bordes;
%       - mapa de disparidad;
%       - gráfico altura vs fecha-hora en vivo;
% 11) compara con alturas manuales de validación;
% 12) guarda CSV, gráfico y videos procesados.
%
% MATLAB R2025b
% Requiere:
% - Computer Vision Toolbox
% - Image Processing Toolbox

clear;
clc;
close all;

%% ============================================================
% CONFIGURACION DEL USUARIO
% =============================================================

CARPETA_BASE = "D:\MDT\Stereovision";

NOMBRE_EXPERIENCIA = "II38P";

ARCHIVO_CALIBRACION = fullfile( ...
    CARPETA_BASE, ...
    "stereoParams.mat" ...
);

% Videos ya grabados.
VIDEO_L = fullfile( ...
    CARPETA_BASE, ...
    NOMBRE_EXPERIENCIA + "_cam1.mp4" ...
);

VIDEO_R = fullfile( ...
    CARPETA_BASE, ...
    NOMBRE_EXPERIENCIA + "_cam2.mp4" ...
);

% CSV con las columnas frame_grabado y timestamp.
CSV_REGISTRO = fullfile( ...
    CARPETA_BASE, ...
    NOMBRE_EXPERIENCIA + "_captura.csv" ...
);

CARPETA_SALIDA = fullfile( ...
    CARPETA_BASE, ...
    NOMBRE_EXPERIENCIA + "_analisis_offline" ...
);

if ~exist(CARPETA_SALIDA, 'dir')
    mkdir(CARPETA_SALIDA);
end

% Altura manual conocida en el instante de referencia.
ALTURA_REFERENCIA_MM = 14.0;

% Fecha y hora correspondiente a esa altura.
TIMESTAMP_REFERENCIA = datetime( ...
    "2026-06-17 19:40:00.000", ...
    "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS" ...
);

% Intervalo temporal que se procesará.
TIMESTAMP_INICIO = datetime( ...
    "2026-06-17 19:39:00.000", ...
    "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS" ...
);

TIMESTAMP_FIN = datetime( ...
    "2026-06-17 20:55:00.000", ...
    "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS" ...
);

% Procesar un frame cada N segundos.
INTERVALO_MUESTREO_S = 1.0;

% true: reproduce el procesamiento en pantalla mientras avanza.
MOSTRAR_PROCESAMIENTO_EN_VIVO = true;

% true: guarda videos procesados.
GUARDAR_VIDEOS_PROCESADOS = true;

% Rango residual de disparitySGM.
MIN_DISPARIDAD = -64;
MAX_DISPARIDAD = 64;

% Alineación horizontal manual después de rectificar.
USAR_ALINEACION_HORIZONTAL_MANUAL = true;

% Selección manual de ROI.
SELECCIONAR_ROI = true;
ROI_FIJA = [180 520 520 380];

% Preprocesamiento
CLAHE_CLIP_LIMIT = 0.012;
CLAHE_NUM_TILES = [8 8];

BILATERAL_DEGREE = 0.05;
BILATERAL_SPATIAL_SIGMA = 3;

% Canny se usa como diagnóstico visual.
CANNY_UMBRAL_BAJO = 0.08;
CANNY_UMBRAL_ALTO = 0.22;

INTENSIDAD_MIN_VALIDA = 8;
INTENSIDAD_MAX_VALIDA = 245;

MIN_PIXELES_VALIDOS = 100;
IQR_FACTOR = 1.5;

% Mediana temporal.
VENTANA_MEDIANA = 5;

% Límites físicos opcionales.
ALTURA_MIN_MM = -20;
ALTURA_MAX_MM = 120;

% Guardado de videos procesados.
PERFIL_VIDEO = "MPEG-4";
CALIDAD_VIDEO = 90;

%% ============================================================
% VALIDACIONES MANUALES
% =============================================================

% Cambia estas filas por tus mediciones manuales reales.
VALIDACIONES = table( ...
    datetime([ ...
        "2026-06-17 20:34:00"
        "2026-06-17 20:50:00" ...
    ], "InputFormat", "yyyy-MM-dd HH:mm:ss"), ...
    [45; 50], ...
    'VariableNames', { ...
        'timestamp', ...
        'altura_manual_mm' ...
    } ...
);

TOLERANCIA_VALIDACION_S = 2.0;

%% ============================================================
% COMPROBAR ARCHIVOS
% =============================================================

archivos = {
    ARCHIVO_CALIBRACION
    VIDEO_L
    VIDEO_R
    CSV_REGISTRO
};

for k = 1:numel(archivos)
    if ~isfile(archivos{k})
        error('No se encontró el archivo: %s', char(archivos{k}));
    end
end

%% ============================================================
% CARGAR CALIBRACION, VIDEOS Y REGISTRO
% =============================================================

datosCal = load(ARCHIVO_CALIBRACION, 'stereoParams');

if ~isfield(datosCal, 'stereoParams')
    error('El archivo MAT no contiene stereoParams.');
end

stereoParams = datosCal.stereoParams;
tamCal = stereoParams.CameraParameters1.ImageSize;

videoL = VideoReader(VIDEO_L);
videoR = VideoReader(VIDEO_R);

if videoL.Width ~= videoR.Width || videoL.Height ~= videoR.Height
    error('Los videos tienen resoluciones diferentes.');
end

registro = readtable( ...
    CSV_REGISTRO, ...
    'VariableNamingRule', ...
    'preserve' ...
);

if ~ismember('frame_grabado', registro.Properties.VariableNames)
    error('El CSV no contiene frame_grabado.');
end

if ~ismember('timestamp', registro.Properties.VariableNames)
    error('El CSV no contiene timestamp.');
end

if ~isdatetime(registro.timestamp)
    try
        registro.timestamp = datetime( ...
            string(registro.timestamp), ...
            'InputFormat', ...
            'yyyy-MM-dd HH:mm:ss.SSS' ...
        );
    catch
        registro.timestamp = datetime(string(registro.timestamp));
    end
end

registro = rmmissing(registro, 'DataVariables', 'timestamp');
registro = sortrows(registro, 'timestamp');

fprintf('\n========================================\n');
fprintf('VIDEOS CARGADOS\n');
fprintf('========================================\n');
fprintf('L: %d x %d, %.3f fps\n', ...
    videoL.Width, videoL.Height, videoL.FrameRate);
fprintf('R: %d x %d, %.3f fps\n', ...
    videoR.Width, videoR.Height, videoR.FrameRate);
fprintf('Calibración: %d x %d\n', tamCal(2), tamCal(1));

%% ============================================================
% FRAME DE REFERENCIA
% =============================================================

coincidenciaRef = buscarFrameMasCercano( ...
    registro, ...
    TIMESTAMP_REFERENCIA ...
);

frameRef = coincidenciaRef.frame_video_matlab;

frameLref = read(videoL, frameRef);
frameRref = read(videoR, frameRef);

[frameLref, frameRref] = adaptarResolucionCalibracion( ...
    frameLref, ...
    frameRref, ...
    tamCal ...
);

[rectLref, rectRref] = rectifyStereoImages( ...
    frameLref, ...
    frameRref, ...
    stereoParams, ...
    'OutputView', ...
    'full' ...
);

%% ============================================================
% ALINEACION HORIZONTAL
% =============================================================

if USAR_ALINEACION_HORIZONTAL_MANUAL
    desplazamientoHorizontalR = seleccionarDesplazamientoHorizontal( ...
        rectLref, ...
        rectRref ...
    );
else
    desplazamientoHorizontalR = 0;
end

rectRref = desplazarHorizontal( ...
    rectRref, ...
    desplazamientoHorizontalR ...
);

%% ============================================================
% ROI
% =============================================================

if SELECCIONAR_ROI
    ROI = seleccionarROI(rectLref);
else
    ROI = ROI_FIJA;
end

fprintf('ROI: [x=%d, y=%d, ancho=%d, alto=%d]\n', ...
    ROI(1), ROI(2), ROI(3), ROI(4));

%% ============================================================
% PROFUNDIDAD DE REFERENCIA
% =============================================================

[dRef, zRef, pixRef, diagRef] = calcularFrame( ...
    rectLref, ...
    rectRref, ...
    stereoParams, ...
    ROI, ...
    MIN_DISPARIDAD, ...
    MAX_DISPARIDAD, ...
    CLAHE_CLIP_LIMIT, ...
    CLAHE_NUM_TILES, ...
    BILATERAL_DEGREE, ...
    BILATERAL_SPATIAL_SIGMA, ...
    CANNY_UMBRAL_BAJO, ...
    CANNY_UMBRAL_ALTO, ...
    INTENSIDAD_MIN_VALIDA, ...
    INTENSIDAD_MAX_VALIDA, ...
    MIN_PIXELES_VALIDOS, ...
    IQR_FACTOR ...
);

if ~isfinite(zRef)
    error(['No se obtuvo profundidad válida en la referencia. ' ...
           'Revisa la ROI y la disparidad.']);
end

fprintf('\n========================================\n');
fprintf('REFERENCIA\n');
fprintf('========================================\n');
fprintf('Timestamp: %s\n', string(TIMESTAMP_REFERENCIA));
fprintf('Altura conocida: %.3f mm\n', ALTURA_REFERENCIA_MM);
fprintf('Disparidad: %.3f px\n', dRef);
fprintf('Profundidad: %.3f mm\n', zRef);
fprintf('Píxeles válidos: %d\n', pixRef);

%% ============================================================
% FRAMES A PROCESAR
% =============================================================

filasIntervalo = registro( ...
    registro.timestamp >= TIMESTAMP_INICIO & ...
    registro.timestamp <= TIMESTAMP_FIN, ...
    : ...
);

if isempty(filasIntervalo)
    error('No hay frames dentro del intervalo temporal.');
end

saltoFrames = max( ...
    1, ...
    round(INTERVALO_MUESTREO_S * videoL.FrameRate) ...
);

indices = 1:saltoFrames:height(filasIntervalo);

framesProcesar = double( ...
    filasIntervalo.frame_grabado(indices) ...
) + 1;

timestampsProcesar = filasIntervalo.timestamp(indices);

nMuestras = numel(framesProcesar);

fprintf('\nMuestras a procesar: %d\n', nMuestras);
fprintf('Intervalo aproximado: %.3f s\n', INTERVALO_MUESTREO_S);

%% ============================================================
% FIGURAS EN VIVO
% =============================================================

if MOSTRAR_PROCESAMIENTO_EN_VIVO
    figProceso = figure( ...
        'Name', ...
        'Procesamiento offline de videos', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'black' ...
    );

    tl = tiledlayout( ...
        figProceso, ...
        2, ...
        3, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact' ...
    );

    axRect = nexttile(tl, 1);
    hRect = imshow(dibujarROI(rectLref, ROI), 'Parent', axRect);
    title(axRect, 'Rectificada izquierda', 'Color', 'white');

    axClahe = nexttile(tl, 2);
    hClahe = imshow(diagRef.claheMontaje, 'Parent', axClahe);
    title(axClahe, 'CLAHE L / R', 'Color', 'white');

    axBordes = nexttile(tl, 3);
    hBordes = imshow(diagRef.bordesMontaje, 'Parent', axBordes);
    title(axBordes, 'Canny L / R', 'Color', 'white');

    axDisp = nexttile(tl, 4);
    hDisp = imshow(diagRef.disparidadColor, 'Parent', axDisp);
    title(axDisp, 'Disparidad', 'Color', 'white');

    axDiag = nexttile(tl, 5);
    hDiag = imshow(diagRef.diagnostico, 'Parent', axDiag);
    title(axDiag, 'Diagnóstico combinado', 'Color', 'white');

    axTexto = nexttile(tl, 6);
    axis(axTexto, 'off');

    hTexto = text( ...
        axTexto, ...
        0.02, ...
        0.95, ...
        'Preparando...', ...
        'Color', ...
        'white', ...
        'FontSize', ...
        12, ...
        'VerticalAlignment', ...
        'top' ...
    );
else
    figProceso = [];
end

figGrafico = figure( ...
    'Name', ...
    'Altura de espuma vs tiempo', ...
    'NumberTitle', ...
    'off', ...
    'Color', ...
    'white' ...
);

axGrafico = axes(figGrafico);
hold(axGrafico, 'on');
grid(axGrafico, 'on');

lineaAltura = animatedline( ...
    axGrafico, ...
    'LineWidth', ...
    1.8, ...
    'DisplayName', ...
    'Altura estimada' ...
);

% animatedline trabaja con valores numéricos en el eje X.
% Por eso las fechas de validación también se convierten a datenum.
fechasValidacionNumericas = datenum(VALIDACIONES.timestamp);

scatter( ...
    axGrafico, ...
    fechasValidacionNumericas, ...
    VALIDACIONES.altura_manual_mm, ...
    70, ...
    'x', ...
    'LineWidth', ...
    1.8, ...
    'DisplayName', ...
    'Validación manual' ...
);

yline( ...
    axGrafico, ...
    ALTURA_REFERENCIA_MM, ...
    '--', ...
    'Referencia', ...
    'DisplayName', ...
    'Altura de referencia' ...
);

xlabel(axGrafico, 'Fecha y hora');
ylabel(axGrafico, 'Altura de espuma [mm]');
title(axGrafico, 'Altura de espuma mediante estereovisión');
legend(axGrafico, 'Location', 'best');
% Formatear el eje numérico como fecha y hora.
datetick(axGrafico, 'x', 'yyyy-mm-dd HH:MM', 'keeplimits');
xtickangle(axGrafico, 35);

%% ============================================================
% VIDEO WRITERS
% =============================================================

if GUARDAR_VIDEOS_PROCESADOS
    fpsSalida = 1 / INTERVALO_MUESTREO_S;

    writerRect = crearWriter( ...
        fullfile(CARPETA_SALIDA, ...
        NOMBRE_EXPERIENCIA + "_rectificado.mp4"), ...
        fpsSalida, ...
        CALIDAD_VIDEO ...
    );

    writerClahe = crearWriter( ...
        fullfile(CARPETA_SALIDA, ...
        NOMBRE_EXPERIENCIA + "_clahe.mp4"), ...
        fpsSalida, ...
        CALIDAD_VIDEO ...
    );

    writerBordes = crearWriter( ...
        fullfile(CARPETA_SALIDA, ...
        NOMBRE_EXPERIENCIA + "_bordes.mp4"), ...
        fpsSalida, ...
        CALIDAD_VIDEO ...
    );

    writerDisp = crearWriter( ...
        fullfile(CARPETA_SALIDA, ...
        NOMBRE_EXPERIENCIA + "_disparidad.mp4"), ...
        fpsSalida, ...
        CALIDAD_VIDEO ...
    );

    writerDiag = crearWriter( ...
        fullfile(CARPETA_SALIDA, ...
        NOMBRE_EXPERIENCIA + "_diagnostico.mp4"), ...
        fpsSalida, ...
        CALIDAD_VIDEO ...
    );
end

%% ============================================================
% PROCESAMIENTO
% =============================================================

timestamp = NaT(nMuestras, 1);
frame_matlab = nan(nMuestras, 1);
disparidad_px = nan(nMuestras, 1);
profundidad_mm = nan(nMuestras, 1);
altura_mm = nan(nMuestras, 1);
altura_filtrada_mm = nan(nMuestras, 1);
pixeles_validos = zeros(nMuestras, 1);

ventanaAltura = nan(VENTANA_MEDIANA, 1);
indiceVentana = 0;

validacionProcesada = false(height(VALIDACIONES), 1);
resultadosValidacion = table();

nFramesMax = floor(min( ...
    videoL.Duration * videoL.FrameRate, ...
    videoR.Duration * videoR.FrameRate ...
));

for i = 1:nMuestras
    idx = framesProcesar(i);

    timestamp(i) = timestampsProcesar(i);
    frame_matlab(i) = idx;

    if idx < 1 || idx > nFramesMax
        continue;
    end

    try
        frameL = read(videoL, idx);
        frameR = read(videoR, idx);
    catch
        continue;
    end

    [frameL, frameR] = adaptarResolucionCalibracion( ...
        frameL, frameR, tamCal);

    [rectL, rectR] = rectifyStereoImages( ...
        frameL, frameR, stereoParams, ...
        'OutputView', 'full');

    rectR = desplazarHorizontal( ...
        rectR, desplazamientoHorizontalR);

    [dMediana, zMediana, nValidos, diagnostico] = ...
        calcularFrame( ...
            rectL, ...
            rectR, ...
            stereoParams, ...
            ROI, ...
            MIN_DISPARIDAD, ...
            MAX_DISPARIDAD, ...
            CLAHE_CLIP_LIMIT, ...
            CLAHE_NUM_TILES, ...
            BILATERAL_DEGREE, ...
            BILATERAL_SPATIAL_SIGMA, ...
            CANNY_UMBRAL_BAJO, ...
            CANNY_UMBRAL_ALTO, ...
            INTENSIDAD_MIN_VALIDA, ...
            INTENSIDAD_MAX_VALIDA, ...
            MIN_PIXELES_VALIDOS, ...
            IQR_FACTOR ...
        );

    disparidad_px(i) = dMediana;
    profundidad_mm(i) = zMediana;
    pixeles_validos(i) = nValidos;

    if isfinite(zMediana)
        alturaCalculada = ALTURA_REFERENCIA_MM + ...
            (zRef - zMediana);

        if alturaCalculada >= ALTURA_MIN_MM && ...
                alturaCalculada <= ALTURA_MAX_MM
            altura_mm(i) = alturaCalculada;
        end
    end

    if isfinite(altura_mm(i))
        indiceVentana = indiceVentana + 1;
        posicion = mod(indiceVentana - 1, VENTANA_MEDIANA) + 1;
        ventanaAltura(posicion) = altura_mm(i);

        altura_filtrada_mm(i) = median( ...
            ventanaAltura, ...
            'omitnan' ...
        );
    end

    % Gráfico en vivo
    if isfinite(altura_filtrada_mm(i))
        addpoints( ...
            lineaAltura, ...
            datenum(timestamp(i)), ...
            altura_filtrada_mm(i) ...
        );
    end

    % Validación automática
    if isfinite(altura_filtrada_mm(i))
        for iv = 1:height(VALIDACIONES)
            if validacionProcesada(iv)
                continue;
            end

            diferenciaS = abs(seconds( ...
                timestamp(i) - VALIDACIONES.timestamp(iv) ...
            ));

            if diferenciaS <= TOLERANCIA_VALIDACION_S
                manual = VALIDACIONES.altura_manual_mm(iv);
                estimada = altura_filtrada_mm(i);

                errorMm = estimada - manual;
                errorAbs = abs(errorMm);

                if abs(manual) > eps
                    errorPct = 100 * errorAbs / abs(manual);
                else
                    errorPct = NaN;
                end

                nuevaFila = table( ...
                    VALIDACIONES.timestamp(iv), ...
                    timestamp(i), ...
                    manual, ...
                    estimada, ...
                    errorMm, ...
                    errorAbs, ...
                    errorPct, ...
                    'VariableNames', { ...
                        'timestamp_manual', ...
                        'timestamp_estimacion', ...
                        'altura_manual_mm', ...
                        'altura_estimada_mm', ...
                        'error_mm', ...
                        'error_absoluto_mm', ...
                        'error_relativo_pct' ...
                    } ...
                );

                resultadosValidacion = [ ...
                    resultadosValidacion; ...
                    nuevaFila ...
                ]; %#ok<AGROW>

                validacionProcesada(iv) = true;

                fprintf('\nVALIDACIÓN %d:\n', iv);
                fprintf('  Manual: %.3f mm\n', manual);
                fprintf('  Estimada: %.3f mm\n', estimada);
                fprintf('  Error: %+.3f mm\n', errorMm);
                fprintf('  Error absoluto: %.3f mm\n', errorAbs);
                fprintf('  Error relativo: %.2f %%\n', errorPct);
            end
        end
    end

    % Actualizar ventana de procesamiento
    if MOSTRAR_PROCESAMIENTO_EN_VIVO && isgraphics(figProceso)
        hRect.CData = dibujarROI(rectL, ROI);
        hClahe.CData = diagnostico.claheMontaje;
        hBordes.CData = diagnostico.bordesMontaje;
        hDisp.CData = diagnostico.disparidadColor;
        hDiag.CData = diagnostico.diagnostico;

        hTexto.String = sprintf([ ...
            'Muestra: %d/%d\n' ...
            'Timestamp: %s\n' ...
            'Frame: %d\n' ...
            'Disparidad: %.3f px\n' ...
            'Profundidad: %.3f mm\n' ...
            'Altura: %.3f mm\n' ...
            'Altura filtrada: %.3f mm\n' ...
            'Píxeles válidos: %d'], ...
            i, ...
            nMuestras, ...
            string(timestamp(i)), ...
            idx, ...
            dMediana, ...
            zMediana, ...
            altura_mm(i), ...
            altura_filtrada_mm(i), ...
            nValidos ...
        );

        datetick(axGrafico, 'x', 'yyyy-mm-dd HH:MM', ...
            'keeplimits', 'keepticks');
        drawnow limitrate;
    else
        datetick(axGrafico, 'x', 'yyyy-mm-dd HH:MM', ...
            'keeplimits', 'keepticks');
        drawnow limitrate;
    end

    % Guardar videos procesados
    if GUARDAR_VIDEOS_PROCESADOS
        writeVideo(writerRect, prepararVideo( ...
            imtile({rectL, rectR}, 'GridSize', [1 2])));

        writeVideo(writerClahe, prepararVideo( ...
            diagnostico.claheMontaje));

        writeVideo(writerBordes, prepararVideo( ...
            diagnostico.bordesMontaje));

        writeVideo(writerDisp, prepararVideo( ...
            diagnostico.disparidadColor));

        writeVideo(writerDiag, prepararVideo( ...
            diagnostico.diagnostico));
    end

    if mod(i, 20) == 0 || i == nMuestras
        fprintf('Procesadas %d/%d muestras\n', i, nMuestras);
    end
end

%% ============================================================
% CERRAR VIDEOS
% =============================================================

if GUARDAR_VIDEOS_PROCESADOS
    close(writerRect);
    close(writerClahe);
    close(writerBordes);
    close(writerDisp);
    close(writerDiag);
end

%% ============================================================
% GUARDAR RESULTADOS
% =============================================================

resultados = table( ...
    timestamp, ...
    frame_matlab, ...
    disparidad_px, ...
    profundidad_mm, ...
    altura_mm, ...
    altura_filtrada_mm, ...
    pixeles_validos ...
);

rutaResultados = fullfile( ...
    CARPETA_SALIDA, ...
    NOMBRE_EXPERIENCIA + "_altura_vs_tiempo.csv" ...
);

writetable(resultados, rutaResultados);

if isempty(resultadosValidacion)
    resultadosValidacion = table( ...
        'Size', [0 7], ...
        'VariableTypes', { ...
            'datetime', ...
            'datetime', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double' ...
        }, ...
        'VariableNames', { ...
            'timestamp_manual', ...
            'timestamp_estimacion', ...
            'altura_manual_mm', ...
            'altura_estimada_mm', ...
            'error_mm', ...
            'error_absoluto_mm', ...
            'error_relativo_pct' ...
        } ...
    );
end

rutaValidacion = fullfile( ...
    CARPETA_SALIDA, ...
    NOMBRE_EXPERIENCIA + "_validacion.csv" ...
);

writetable(resultadosValidacion, rutaValidacion);

rutaGrafico = fullfile( ...
    CARPETA_SALIDA, ...
    NOMBRE_EXPERIENCIA + "_altura_vs_tiempo.png" ...
);

exportgraphics( ...
    figGrafico, ...
    rutaGrafico, ...
    'Resolution', ...
    300 ...
);

rutaMAT = fullfile( ...
    CARPETA_SALIDA, ...
    NOMBRE_EXPERIENCIA + "_resultado.mat" ...
);

save( ...
    rutaMAT, ...
    'resultados', ...
    'resultadosValidacion', ...
    'VALIDACIONES', ...
    'ROI', ...
    'zRef', ...
    'dRef', ...
    'ALTURA_REFERENCIA_MM', ...
    'desplazamientoHorizontalR', ...
    'stereoParams' ...
);

fprintf('\n========================================\n');
fprintf('FINALIZADO\n');
fprintf('========================================\n');
fprintf('Resultados:\n%s\n', rutaResultados);
fprintf('Validación:\n%s\n', rutaValidacion);
fprintf('Gráfico:\n%s\n', rutaGrafico);
fprintf('MAT:\n%s\n', rutaMAT);

%% ============================================================
% FUNCIONES LOCALES
% =============================================================

function coincidencia = buscarFrameMasCercano( ...
    registro, timestampObjetivo)

    diferencias = abs(seconds( ...
        registro.timestamp - timestampObjetivo ...
    ));

    [diferenciaMin, idx] = min(diferencias);

    frameGrabado = double(registro.frame_grabado(idx));

    coincidencia.timestamp_encontrado = registro.timestamp(idx);
    coincidencia.diferencia_s = diferenciaMin;
    coincidencia.frame_grabado_csv = frameGrabado;
    coincidencia.frame_video_matlab = frameGrabado + 1;
end


function [frameLout, frameRout] = adaptarResolucionCalibracion( ...
    frameL, frameR, tamCal)

    if ~isequal(size(frameL, 1:2), tamCal)
        frameLout = imresize(frameL, tamCal);
    else
        frameLout = frameL;
    end

    if ~isequal(size(frameR, 1:2), tamCal)
        frameRout = imresize(frameR, tamCal);
    else
        frameRout = frameR;
    end
end


function desplazamientoR = seleccionarDesplazamientoHorizontal( ...
    rectL, rectR)

    f1 = figure('Name', 'Punto cámara izquierda');
    imshow(rectL);
    title('Selecciona un detalle en la cámara izquierda');
    [xL, yL] = ginput(1);
    close(f1);

    f2 = figure('Name', 'Punto cámara derecha');
    imshow(rectR);
    title('Selecciona el mismo detalle en la cámara derecha');
    [xR, yR] = ginput(1);
    close(f2);

    desplazamientoR = xL - xR;

    fprintf('\nAlineación manual:\n');
    fprintf('xL=%.3f, yL=%.3f\n', xL, yL);
    fprintf('xR=%.3f, yR=%.3f\n', xR, yR);
    fprintf('Diferencia vertical informativa: %.3f px\n', abs(yL-yR));
    fprintf('Desplazamiento horizontal: %.3f px\n', desplazamientoR);
end


function salida = desplazarHorizontal(imagen, desplazamientoX)
    salida = imtranslate( ...
        imagen, ...
        [desplazamientoX 0], ...
        'OutputView', ...
        'same', ...
        'FillValues', ...
        0 ...
    );
end


function ROI = seleccionarROI(imagen)
    f = figure('Name', 'Seleccionar ROI de espuma');
    imshow(imagen);
    title('Selecciona la ROI de la superficie/espuma');
    h = drawrectangle('Color', 'yellow');
    wait(h);
    ROI = round(h.Position);
    close(f);

    ROI(1) = max(1, ROI(1));
    ROI(2) = max(1, ROI(2));
    ROI(3) = max(1, ROI(3));
    ROI(4) = max(1, ROI(4));

    ROI(3) = min(ROI(3), size(imagen,2)-ROI(1)+1);
    ROI(4) = min(ROI(4), size(imagen,1)-ROI(2)+1);
end


function [dMediana, zMediana, nValidos, diagnostico] = ...
    calcularFrame( ...
        rectL, ...
        rectR, ...
        stereoParams, ...
        ROI, ...
        minD, ...
        maxD, ...
        clipLimit, ...
        numTiles, ...
        bilateralDegree, ...
        bilateralSigma, ...
        cannyBajo, ...
        cannyAlto, ...
        intensidadMin, ...
        intensidadMax, ...
        minPixeles, ...
        iqrFactor)

    grayOriginalL = im2gray(rectL);
    grayOriginalR = im2gray(rectR);

    claheL = adapthisteq( ...
        grayOriginalL, ...
        'ClipLimit', ...
        clipLimit, ...
        'NumTiles', ...
        numTiles ...
    );

    claheR = adapthisteq( ...
        grayOriginalR, ...
        'ClipLimit', ...
        clipLimit, ...
        'NumTiles', ...
        numTiles ...
    );

    claheL = imbilatfilt( ...
        claheL, ...
        bilateralDegree, ...
        bilateralSigma ...
    );

    claheR = imbilatfilt( ...
        claheR, ...
        bilateralDegree, ...
        bilateralSigma ...
    );

    bordesL = edge( ...
        claheL, ...
        'Canny', ...
        [cannyBajo cannyAlto] ...
    );

    bordesR = edge( ...
        claheR, ...
        'Canny', ...
        [cannyBajo cannyAlto] ...
    );

    disparityMap = disparitySGM( ...
        claheL, ...
        claheR, ...
        'DisparityRange', ...
        [minD maxD], ...
        'UniquenessThreshold', ...
        10 ...
    );

    intensidadValida = ...
        grayOriginalL >= intensidadMin & ...
        grayOriginalL <= intensidadMax & ...
        grayOriginalR >= intensidadMin & ...
        grayOriginalR <= intensidadMax;

    invalidos = ...
        ~isfinite(disparityMap) | ...
        disparityMap <= minD + 2 | ...
        disparityMap >= maxD - 2 | ...
        ~intensidadValida;

    disparityMap(invalidos) = NaN;

    xyz = reconstructScene( ...
        disparityMap, ...
        stereoParams ...
    );

    x = ROI(1);
    y = ROI(2);
    w = ROI(3);
    h = ROI(4);

    x2 = min(size(disparityMap,2), x+w-1);
    y2 = min(size(disparityMap,1), y+h-1);

    roiD = disparityMap(y:y2, x:x2);
    roiZ = xyz(y:y2, x:x2, 3);

    validos = isfinite(roiD) & ...
              isfinite(roiZ) & ...
              roiZ > 0;

    valoresD = double(roiD(validos));
    valoresZ = double(roiZ(validos));

    nValidos = numel(valoresZ);

    if nValidos >= minPixeles
        mascara = mascaraIQR( ...
            valoresZ, ...
            iqrFactor ...
        );

        valoresD = valoresD(mascara);
        valoresZ = valoresZ(mascara);
        nValidos = numel(valoresZ);
    end

    if nValidos < minPixeles
        dMediana = NaN;
        zMediana = NaN;
    else
        dMediana = median(valoresD, 'omitnan');
        zMediana = median(valoresZ, 'omitnan');
    end

    claheMontaje = imtile( ...
        {claheL, claheR}, ...
        'GridSize', ...
        [1 2] ...
    );

    bordesMontaje = imtile( ...
        {bordesL, bordesR}, ...
        'GridSize', ...
        [1 2] ...
    );

    disparidadColor = colorearDisparidad( ...
        disparityMap, ...
        minD, ...
        maxD ...
    );

    disparidadColor = dibujarROI( ...
        disparidadColor, ...
        ROI ...
    );

    diagnosticoImagen = crearDiagnostico( ...
        rectL, ...
        claheL, ...
        bordesL, ...
        disparidadColor, ...
        ROI ...
    );

    diagnostico.claheMontaje = claheMontaje;
    diagnostico.bordesMontaje = bordesMontaje;
    diagnostico.disparidadColor = disparidadColor;
    diagnostico.diagnostico = diagnosticoImagen;
end


function mascara = mascaraIQR(valores, factor)
    q1 = prctile(valores, 25);
    q3 = prctile(valores, 75);
    rango = q3 - q1;

    if rango <= 0
        mascara = true(size(valores));
        return;
    end

    mascara = valores >= q1-factor*rango & ...
              valores <= q3+factor*rango;
end


function salida = colorearDisparidad(dispMap, minD, maxD)
    normalizada = (dispMap - minD) / (maxD - minD);
    normalizada = max(0, min(1, normalizada));
    normalizada(~isfinite(normalizada)) = 0;

    indice = uint8(round(normalizada * 255));
    mapa = turbo(256);

    salida = ind2rgb(indice + 1, mapa);
    salida = im2uint8(salida);
end


function salida = dibujarROI(imagen, ROI)
    salida = imagen;

    if size(salida,3) == 1
        salida = repmat(salida, [1 1 3]);
    end

    salida = insertShape( ...
        salida, ...
        'Rectangle', ...
        ROI, ...
        'Color', ...
        'yellow', ...
        'LineWidth', ...
        3 ...
    );
end


function diagnostico = crearDiagnostico( ...
    rectL, claheL, bordesL, dispColor, ROI)

    rectMarcada = dibujarROI(rectL, ROI);

    claheRGB = repmat(claheL, [1 1 3]);
    claheRGB = dibujarROI(claheRGB, ROI);

    bordesRGB = repmat(uint8(bordesL)*255, [1 1 3]);
    bordesRGB = dibujarROI(bordesRGB, ROI);

    objetivo = [480 640];

    a = imresize(rectMarcada, objetivo);
    b = imresize(claheRGB, objetivo);
    c = imresize(bordesRGB, objetivo);
    d = imresize(dispColor, objetivo);

    diagnostico = [a b; c d];
end


function writer = crearWriter(ruta, fps, calidad)
    writer = VideoWriter(ruta, 'MPEG-4');
    writer.FrameRate = fps;

    if isprop(writer, 'Quality')
        writer.Quality = calidad;
    end

    open(writer);
end


function frame = prepararVideo(frame)
    if islogical(frame)
        frame = uint8(frame) * 255;
    elseif isa(frame, 'double') || isa(frame, 'single')
        frame = im2uint8(frame);
    end

    if size(frame,3) == 1
        frame = repmat(frame, [1 1 3]);
    end

    if mod(size(frame,1),2) ~= 0
        frame = frame(1:end-1,:,:);
    end

    if mod(size(frame,2),2) ~= 0
        frame = frame(:,1:end-1,:);
    end
end
